image: docker:latest

services:
  - docker:dind

before_script:
  - apk add --no-cache openssh-client

deploy:
  stage: deploy
  script:
    - echo "$SSH_PRIVATE_KEY" > ssh_key
    - chmod 600 ssh_key
    - ssh -o "StrictHostKeyChecking=no" -i ssh_key $SSH_USER@$SSH_IP "sudo su;chmod +x /home/projects/pos-system/deploy/deploy.sh;/home/projects/pos-system/deploy/deploy.sh $CI_PROJECT_NAMESPACE $CI_PROJECT_NAME"


